// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsKnX_dI8RYGhSxmYNc5pt-0HNCHqXffE',
    appId: '1:216558823734:web:38c5afec04b4ae4bcbab97',
    messagingSenderId: '216558823734',
    projectId: 'todo-database-90d12',
    authDomain: 'todo-database-90d12.firebaseapp.com',
    storageBucket: 'todo-database-90d12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJtLAqnU153YdNRS_cqwdXz5B9sU8bBc',
    appId: '1:216558823734:android:3c7305694f353dc3cbab97',
    messagingSenderId: '216558823734',
    projectId: 'todo-database-90d12',
    storageBucket: 'todo-database-90d12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5hKIHSfVM1aY2slDZO1XsMDD7TdH2Yw',
    appId: '1:216558823734:ios:c68c009c35d780cacbab97',
    messagingSenderId: '216558823734',
    projectId: 'todo-database-90d12',
    storageBucket: 'todo-database-90d12.appspot.com',
    iosClientId: '216558823734-gm7uf740fh4jnkaa5mbu53i9nu4kkirh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ5hKIHSfVM1aY2slDZO1XsMDD7TdH2Yw',
    appId: '1:216558823734:ios:c68c009c35d780cacbab97',
    messagingSenderId: '216558823734',
    projectId: 'todo-database-90d12',
    storageBucket: 'todo-database-90d12.appspot.com',
    iosClientId: '216558823734-gm7uf740fh4jnkaa5mbu53i9nu4kkirh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
